### ISSUE TITLE
IPv6 Support Progress Tracking

### ISSUE THREAD

**Issue by LiangZugeng** [aliyun/terraform-provider-alicloud#2998]
### Terraform Version
0.13.5

### Affected Resource(s)
- alicloud_vpc

### Expected Behavior
IPv6 Gateway should be supported, currently there is no way to configure IPv6 Gateway under a VPC using Terraform

### Actual Behavior
There is no resource in alicloud provider to manipulate IPv6 settings for a VPC

Is it something that I missed or the current provider actually doesn't support IPv6 for a VPC? If it doesn't support IPv6 please kindly give us an estimation on the delivery time frame for this feature. Thanks.

**Comment by LiangZugeng** [comment]
Went through the docs again, seems IPv6 is totally unsupported not only for VPC but also for ECS, vSwitch etc.

Could anyone here from Alibaba Cloud provide some relevant information?

**Comment by LiangZugeng** [comment]
I worked on the security group rule resource today and found there is no IPv6 support on this resource neither. The official document clearly states: "cidr_ip - (Optional, ForceNew) The target IP address range. The default value is 0.0.0.0/0 (which means no restriction will be applied). Other supported formats include 10.159.6.18/12. Only IPv4 is supported."

It appears that Alicloud Terraform provider currently doesn't have IPv6 support at all, Since we are using v4/v6 dual stack to provide services to our customers, no IPv6 support from the provider prevents us using Terraform to provision the infrastructure, hopefully there is a plan and time table to add the IPv6 support, the question is - when?

**Comment by LiangZugeng** [comment]
It's been more than 2 months, anyone here can give us some info regarding IPv6 support of this provider? So far I cannot find any IPv6 resources in the provider.

**Comment by jcyph3r** [comment]
Lack of IPv6 support in alibaba/alicloud seems to be a problem.

**Comment by ezio-ballarin** [comment]
@LiangZugeng[ I made a PR ](https://github.com/aliyun/terraform-provider-alicloud/pull/3427)as a start to adding IPv6 in some places in the provider. There's an argument on resource/alicloud_vpc to enable IPv6, but that's about it. I agree, we should build out IPv6 more for this provider. Especially when it is available in Alibaba's API and just needs the proper go code to tie things together.

**Comment by LiangZugeng** [comment]
@ezio-ballarin thanks for the reply, it's great to see the IPv6 starts to be added into alicloud provider, we will make use of this feature once it get released and I'm looking forward to it.

**Comment by xiaozhu36** [comment]
HI @ezio-ballarin Actually, this PR will have a diff bug that schema supports to input ipv6_cidr with an `int` value but the api will return a whole ipv6 cidr with a `string`. We are pushing the product team to correct it or provide a solution.

**Comment by LiangZugeng** [comment]
@xiaozhu36 Any progress on the resolution of ipv6 cidr type mismatch?

**Comment by LiangZugeng** [comment]
Hi, me again.

Since the date I opened the issue, there has been almost a year, I wonder if we can get an update on the plan or a roadmap regarding adding IPv6 support to various resources?

So far there has been very limited supports on IPv6 in Aliyun Terraform provider, the latest support info is as follows:
1. VPC: enable_ipv6 has been added, but there is no way to set the IPv6 cidr block, plus enable_ipv6 can't be set along with cidr_block.
2. vSwitch: no IPv6 support
3. ECS: no IPv6 support
4. Gateway: No IPv6 gateway resource

I don't mean to push developers of Aliyun Terraform provider on the supporting of IPv6 any sooner, just want to get a picture on how this has been planned internally in the Aliyun team, thanks.

**Comment by LiangZugeng** [comment]
Thanks the dev team for adding alicloud_vpc_ipv6_internet_bandwidth resource.

Now the IPv6 support progress is as follows:

- [ ] alicloud_vpc: enable_ipv6 has been added, however, enable_ipv6 can't be set along with cidr_block for IPv4.

- [ ] alicloud_vswitch: no IPv6 support

- [ ] alicloud_instance: no IPv6 support

- [ ] alicloud_security_group_rule: no IPv6 support

**Comment by jbg** [comment]
Any progress report on this?

**Comment by LiangZugeng** [comment]
> Any progress report on this?

There hasn't been much progress so far, the IPv6 support has long been provided by the Alibaba Cloud API, for example, the elastic network interface API provides [Ipv6AddressCount and Ipv6Address.N parameters](https://www.alibabacloud.com/help/en/elastic-compute-service/latest/createnetworkinterface) to set IPv6 address(es), but there is no equivalent support on [`alicloud_network_interface` resource](https://registry.terraform.io/providers/aliyun/alicloud/latest/docs/resources/network_interface) in Aliyun Terraform provider.

As of today, there is no way, as I know, to enable IPv6 support when creating ECS instance via Terraform. It's supposably the first batch of Terraform resource to support IPv6.

If you are in China and would like to support IPv4/IPv6 dual-stack in Aliyun, Terraform is currently not the best way to automate your infrastructure, instead you can switch to Aliyun's own Resource Orchestration Service.

That being said, Aliyun still has the best Terraform support among cloud vendors in China mainland.

**Comment by zhangyoufu** [comment]
Some progress after years:
* `alicloud_instance` got `ipv6_addresses` & `ipv6_address_count` since 1.193.0.
* `alicloud_security_group_rule` got `ipv6_cidr_ip` since 1.174.0.

**Comment by jksprattler** [comment]
Any status update on supporting the `icmpv6` ip_protocol?

**Comment by xuzhang3** [comment]
This issue has been resolved and the feature/fix has been released. Closing as completed.

**Comment by xuzhang3** [comment]
"(This issue has been ...)"

**Comment by xuzhang3** [comment]
Completed
